name: "Deploy iOS app"

# Trigger the workflow on completion of the CI workflow
on:
  workflow_run:
    workflows: ["Build iOS app"]
    types:
      - completed

jobs:
  deploy:
    runs-on: macos-latest # Use the latest macOS environment
    steps:
      # Initial setup step
      - name: Set up job
        run: echo "Setting up job..."

      # Enable debug logging
      - name: Set debug logging
        run: echo "##[debug]Logging enabled"

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Ruby and Fastlane
      - name: Install Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      # Install Fastlane dependencies
      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      # Download the built IPA file from S3
      - name: Download application from S3
        run: |
          aws s3 cp s3://${{ secrets.AWS_BUCKET_NAME }}/list-for-ios.ipa $RUNNER_TEMP/list-for-ios.ipa
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Deploy the app to TestFlight using Fastlane
      - name: Deploy to TestFlight
        env:
          KEYCHAIN_PATH: $RUNNER_TEMP/app-signing.keychain-db
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # Fastlane match password if using match
        run: |
          bundle exec fastlane upload_to_testflight

      # Final step to indicate job completion
      - name: Complete job
        run: echo "Job complete"
