name: "Deploy iOS app"

on:
  workflow_run:
    workflows: ["Build iOS app"]
    types:
      - completed

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: brew install awscli

      - name: Download latest IPA from S3
        run: |
          LATEST_IPA=$(aws s3 ls s3://${{ secrets.AWS_S3_BUCKET }}/ipa/ --recursive | sort | tail -n 1 | awk '{print $4}')
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/$LATEST_IPA $RUNNER_TEMP/list-for-ios.ipa
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Install Ruby and Fastlane
        run: |
          brew install ruby
          gem install bundler
          bundle install

      - name: Install Fastlane dependencies
        run: bundle exec fastlane install

      - name: Upload to TestFlight
        run: bundle exec fastlane upload_ipa_to_testflight

      - name: Complete job
        run: echo "Job complete"
