name: "CD - Deploy iOS app"

on:
  workflow_run:
    workflows: ["CI - Build iOS app"]
    types:
      - completed

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Set up job
        run: echo "Setting up job..."

      - name: Set debug logging
        run: echo "##[debug]Logging enabled"

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: ${{ runner.temp }}/build

      - name: Install dependencies
        run: sudo gem install xcodeproj

      - name: Deploy to App Store
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
        run: |
          cd ${{ runner.temp }}/build
          xcrun altool --upload-app --type ios --file list-for-ios.ipa --apiKey ${{ secrets.APP_STORE_CONNECT_KEY_ID }} --apiIssuer ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }} --apiKeyFile ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
