name: "Deploy iOS app"

# Trigger the workflow after the CI workflow completes
on:
  workflow_run:
    workflows: ["Build iOS app"]
    types:
      - completed

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      # Initial setup step
      - name: Set up job
        run: echo "Setting up job..."

      # Enable debug logging
      - name: Set debug logging
        run: echo "##[debug]Logging enabled"

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Ruby and Fastlane
      - name: Install Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Fastlane dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install

      # Download the IPA file from S3
      - name: Download from S3
        run: |
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/ipa/list-for-ios.ipa $RUNNER_TEMP/list-for-ios.ipa
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Upload the app to TestFlight using Fastlane
      - name: Deploy to TestFlight
        env:
          KEYCHAIN_PATH: $RUNNER_TEMP/app-signing.keychain-db
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # Fastlane match password if using match
        run: |
          bundle exec fastlane upload_to_testflight

      # Final step to indicate job completion
      - name: Complete job
        run: echo "Job complete"
