name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_with_signing:
    runs-on: macos-latest

    steps:
      - name: Set debug logging
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install -g @ionic/cli @capacitor/assets
          npm install

      - name: Add iOS platform
        run: npx cap add ios

      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Install the Apple certificate and provisioning profile
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          bundle exec fastlane match appstore --readonly --shallow_clone

      - name: Build Ionic app
        run: |
          ionic build
          npx cap sync ios

      - name: Build and sign iOS app using Fastlane
        run: bundle exec fastlane build
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          KEYCHAIN_PATH: $RUNNER_TEMP/app-signing.keychain-db
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Export the archive
        run: |
          xcodebuild -exportArchive \
            -archivePath $RUNNER_TEMP/App.xcarchive \
            -exportPath $RUNNER_TEMP/App \
            -exportOptionsPlist ios/App/exportOptions.plist \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="YOUR_PROVISIONING_PROFILE_NAME" \
            DEVELOPMENT_TEAM="YOUR_DEVELOPMENT_TEAM_ID" \
            OTHER_CODE_SIGN_FLAGS="--keychain $KEYCHAIN_PATH"
