name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Ionic CLI and Capacitor assets
        run: npm install -g @ionic/cli @capacitor/assets

      - name: Install dependencies
        run: npm install

      - name: Build Ionic app
        run: |
          ionic build
          npx cap sync ios

      - name: Build and Archive iOS app
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -sdk iphoneos -configuration Release archive -archivePath $PWD/build/App.xcarchive
