name: Documentation Update

on:
  workflow_run:
    workflows: 
      - Continuous Integration
      - Continuous Deployment
    types:
      - completed

jobs:
  update-readme:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get workflow run info
        id: get_info
        run: |
          echo "WORKFLOW_NAME=${{ github.event.workflow_run.name }}" >> $GITHUB_ENV
          echo "CONCLUSION=${{ github.event.workflow_run.conclusion }}" >> $GITHUB_ENV
          echo "WORKFLOW_RUN_ID=${{ github.event.workflow_run.id }}" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          TIMESTAMP=$(date)
          echo "## Workflow Run - $TIMESTAMP" >> README.md
          echo "- **Workflow Name:** ${{ env.WORKFLOW_NAME }}" >> README.md
          echo "- **Conclusion:** ${{ env.CONCLUSION }}" >> README.md
          echo "- **Workflow Run ID:** ${{ env.WORKFLOW_RUN_ID }}" >> README.md
          echo "- **Commit Message:** ${{ env.COMMIT_MESSAGE }}" >> README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Updated README with workflow run information"
          git push
